### PR TITLE
feat: add request count to chain dropdown

### PR DESCRIPTION
**Pull request by daywiss**
Signed-off-by: David <david@umaproject.org>

image

### CODE REVIEW

**Comment by smb2796** [comment]
Can we use colons `:` instead of dashes? I think it would look nicer

**Comment by daywiss** [comment]
> Can we use colons : instead of dashes? I think it would look nicer. Wdyt?
Yep will do

**Review by smb2796 — APPROVED** [review]
LGTM!

**Review by ryanwolhuter — APPROVED** [review]
very nice as always

**Pull request merged**
