### PR TITLE
feat: add chain based filtering to index page

### PR DESCRIPTION
**Pull request by daywiss**
Signed-off-by: David <david@umaproject.org>

This adds a very simple dropdown filter for the chain you want to see.

image

image

### CODE REVIEW

**Review by ryanwolhuter — APPROVED** [review]
clean, cool and nice 🔥

**Comment by smb2796** [comment]
Looks good. How difficult would it be to not show networks that have no active requests? So where `All = 0`, just not show in dropdown list.

**Comment by daywiss** [comment]
> Looks good. How difficult would it be to not show networks that have no active requests? So where All = 0, just not show in dropdown list.

I can probably do something where i show the count of requests per chain in the drop down, which might be a bit easier, so the user can see that the chain is supported but there are no requests. wdyt

**Comment by daywiss** [comment]
will add this as a new pr

**Pull request merged**
